In [1]:
import numpy as np

In [2]:
a = [1, 5, 6, 8, 2, 4]

In [3]:
# Converting the list to 1 dimensional array. There is an optional parameter of dtype also.

b = np.array(a)

In [4]:
# Printing the dimensions of b

b.shape

(6,)

In [5]:
# Converting the 1 dimensional array.
# It will show array if you try to split into x1 x x2 where x1 * x2 != len(b). You can pass any number of dimensions
# as long as their products remain len(b)

b.reshape(3, 2, 1)

array([[[1],
        [5]],

       [[6],
        [8]],

       [[2],
        [4]]])

In [6]:
# We can use np.ravel() to change a 2 or more dimensional array into one dimesional array.
np.ravel(b)

array([1, 5, 6, 8, 2, 4])

## Indexing is same as that of arrays in C/C++

In [7]:
c = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
c

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [8]:
# Splitting based on indexes. There should be as many colons in it as the dimensions of the array.
# The value on the left and the right shows correspondingly the lower and upperbound of indexes to split.
# If no value is specified to the left of the colon it is considered 0 and for the right it is considered till end.
# The value to the right of the colon is excluded.

d = c[0:,0:1]
d

array([[1],
       [4],
       [7]])

In [9]:
# To access the element at a particular index.
c[1, 1]

5

In [10]:
d

array([[1],
       [4],
       [7]])

In [11]:
# Similar to iota in C++. An array ranging from start to end (excluded).
# Lower bound is taken to be zero if not provided and the optional parameter step is there with default value 1.

np.arange(10, 11, step = 1)

array([10])

In [12]:
# The right border is not excluded. It returns an np array of size 6 with value points that are equally spaced
# including the borders.

np.linspace(1, 12, 6)

array([ 1. ,  3.2,  5.4,  7.6,  9.8, 12. ])

In [13]:
e = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])

# This will replace all the elements from index 3 till end with 100.

e[3:] = 100

print(e)

[  1   2   3 100 100 100 100 100 100 100]


In [14]:
# Numpy arrays are of referene type. It means that when we do f = e and make changes in f, the changes are reflected 
# in e as well.

# For this purpose there is a copy method which creates a copy of the original array.

g = e.copy()

In [15]:
# Using e % 2, e + 2, e - 2, e / 2, we can modify the values of all the elements of the array at once.

print(e * 2)

[  2   4   6 200 200 200 200 200 200 200]


In [16]:
# Uses random distribution to generate the numbers between [0, 1]
# The parameter is basically a shape.
# Use np.random.rand(4, 4) for creating a 4 x 4 matrix.

np.random.rand(3)

array([0.26289026, 0.21910951, 0.87523181])

In [17]:
# np.ones(5) creates an array of ones with length 5
# There is an optional parameter for the data type.

np.ones(5, dtype = float)

# For two or more dimensional matrix of ones.
np.ones(4, dtype = int)

array([1, 1, 1, 1])

In [18]:
# np.identity(5) creates an identity matrix of 5 x 5.
# There is an optional parameter for the data type.

np.identity(5, dtype = float)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [19]:
# Uses standard normal distribution to generate the numbers.
# The parameter is basically a shape.

np.random.randn(4, 4)

array([[-0.24719741, -0.73227158, -1.69907478,  0.60149564],
       [ 0.27188021, -0.89782979,  1.91309348, -0.58640219],
       [-0.71745702, -0.19427098, -0.70055628, -0.59005374],
       [-0.80135046,  0.81293319, -1.13791133,  0.23304363]])

In [20]:
# Generating random integers between a range.
# The left border is inclusive while the right isn't.
# The third parameter is the length of the returned numpy array.

h = np.random.randint(0, 8, 5)

h

array([3, 6, 0, 6, 3])

In [21]:
# h.argmax() and h.argmin() will return the index of the maximum and minimum element in the array

print(h.argmax())

print(h.argmin())

1
2


In [22]:
# If there are two numpy arrays A and B. Then we can perform the matrix computations like addition, subtraction 
# and multiplication if the corresponding dimensions are valid.

A = np.array([[1, 3, 0], [5, 1, 1]])
B = np.array([[4, 1, 1], [1, 0, 0]])

A + B

array([[5, 4, 1],
       [6, 1, 1]])

In [23]:
# It returns a tuple of all the indexes where the condition is satisfied.

np.where(A > 2)

(array([0, 1]), array([1, 0]))